apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsobuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsobuggy
  template:
    metadata:
      labels:
        app: dsobuggy
    spec:
      containers:
      - name: dsobuggy
        image: 074832285117.dkr.ecr.us-west-2.amazonaws.com/dsoecrrepo
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dsobuggy
    k8s-app: dsobuggy
  name: dsobuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: dsobuggy
